version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'
      time: '16:42'
      timezone: 'Brazil/East'
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'chore(deps):'
      include: 'scope'
